version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: axeunder/kittygram_backend
    env_file: .env
    volumes:
      - static_valume:/backend_static
  frontend:
    env_file: .env
    image: axeunder/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: axeunder/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_valume:/staticfiles
